.PHONY: setup up up-direct down logs reset provision configure-gateway tf-init tf-plan tf-apply config ps verify verify-topology check-repos

COMPOSE = docker compose --env-file .env --env-file .env.generated

-include .env
-include .env.generated

SHELL_PORT ?= 3000
MS_AUTH_PORT ?= 3001
MFE_AUTH_PORT ?= 4001
MINISTACK_PORT ?= 4566

SHELL_URL ?= http://localhost:$(SHELL_PORT)
AUTH_API_URL ?= $(AUTH_API_PUBLIC_URL)
AUTH_API_PUBLIC_URL ?= http://localhost:$(MS_AUTH_PORT)
MFE_AUTH_URL ?= http://localhost:$(MFE_AUTH_PORT)
MINISTACK_URL ?= http://localhost:$(MINISTACK_PORT)

setup: .env .env.generated check-repos
	$(COMPOSE) up -d --build postgres ministack chave-ms-auth
	@./scripts/configure-ministack-gateway.sh
	$(COMPOSE) up -d --build chave-mfe-auth chave-shell
	@echo "[make] Stack started."
	@echo "[make] Shell:     $(SHELL_URL)"
	@echo "[make] Auth MFE:  $(MFE_AUTH_URL)"
	@auth_api_url="$$(grep -E '^AUTH_API_PUBLIC_URL=' .env.generated | tail -n 1 | cut -d= -f2-)"; \
		echo "[make] Auth API:  $$auth_api_url"; \
		echo "[make] Swagger:   $$auth_api_url/docs"
	@echo "[make] Ministack: $(MINISTACK_URL)"

up: setup

up-direct: .env .env.generated check-repos
	$(COMPOSE) up -d --build

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

reset: .env .env.generated check-repos
	$(COMPOSE) down -v --remove-orphans
	$(COMPOSE) up -d --build postgres ministack chave-ms-auth
	@./scripts/configure-ministack-gateway.sh
	$(COMPOSE) up -d --build chave-mfe-auth chave-shell

provision: .env .env.generated
	$(COMPOSE) up -d ministack
	$(COMPOSE) --profile provision run --rm infra-provisioner

configure-gateway: .env .env.generated
	@./scripts/configure-ministack-gateway.sh

tf-init: .env .env.generated
	$(COMPOSE) up -d ministack
	$(COMPOSE) --profile provision run --rm --entrypoint terraform infra-provisioner init

tf-plan: .env .env.generated
	$(COMPOSE) up -d ministack
	$(COMPOSE) --profile provision run --rm --entrypoint terraform infra-provisioner plan

tf-apply: provision

config: .env .env.generated
	$(COMPOSE) config

ps:
	$(COMPOSE) ps

verify: .env .env.generated
	@./scripts/verify-stack.sh endpoints

verify-topology: .env .env.generated
	@./scripts/verify-stack.sh topology

check-repos:
	@missing=0; \
	for dockerfile in ../chave-ms-auth-g1/Dockerfile ../chave-mfe-auth-g1/Dockerfile ../chave-shell-g1/Dockerfile; do \
		if [ ! -f "$$dockerfile" ]; then \
			echo "[make] Missing required sibling Dockerfile: $$dockerfile"; \
			missing=1; \
		elif grep -q "npm ci" "$$dockerfile"; then \
			lockfile="$$(dirname "$$dockerfile")/package-lock.json"; \
			if [ ! -f "$$lockfile" ]; then \
				echo "[make] Missing npm lockfile required by '$$dockerfile': $$lockfile"; \
				missing=1; \
			fi; \
		fi; \
	done; \
	if [ "$$missing" = "1" ]; then \
		echo "[make] Clone, restore, or regenerate the sibling application repositories next to chave-infra."; \
		exit 1; \
	fi

.env:
	@if [ ! -f .env ]; then \
		echo "[make] .env not found; copying .env.example."; \
		cp .env.example .env; \
	fi

.env.generated:
	@if [ ! -f .env.generated ]; then \
		echo "# Generated by make configure-gateway." > .env.generated; \
		echo "AUTH_API_PUBLIC_URL=http://localhost:$(MS_AUTH_PORT)" >> .env.generated; \
	fi
