#!/bin/sh
set -eu

output_file=".env.generated"

info() {
  echo "[gateway] $*"
}

fail() {
  echo "[gateway] ERROR: $*" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || fail "docker is required"

ministack_port="${MINISTACK_PORT:-4566}"

if [ ! -f .env ]; then
  info ".env not found; copying .env.example."
  cp .env.example .env
fi

if [ ! -f "$output_file" ]; then
  {
    echo "# Generated by scripts/configure-ministack-gateway.sh."
    echo "AUTH_API_PUBLIC_URL=http://localhost:${ministack_port}"
  } > "$output_file"
fi

info "Provisioning Ministack API Gateway resources."
docker compose --env-file .env --env-file "$output_file" --profile provision run --rm infra-provisioner

gateway_url="$(docker compose --env-file .env --env-file "$output_file" --profile provision run --rm --entrypoint terraform infra-provisioner output -raw gateway_url)"

if [ -z "$gateway_url" ]; then
  fail "Terraform did not return a gateway_url output"
fi

case "$gateway_url" in
  http://localhost:*|http://127.0.0.1:*) ;;
  http://ministack:*)
    gateway_url="$(printf '%s' "$gateway_url" | sed "s#http://ministack:4566#http://localhost:${ministack_port}#")"
    ;;
  *)
    info "Using non-localhost gateway URL returned by Terraform: $gateway_url"
    ;;
esac

cat > "$output_file" <<EOF
# Generated by scripts/configure-ministack-gateway.sh.
# Do not commit this file; it contains machine-local generated URLs.
AUTH_API_PUBLIC_URL=${gateway_url}
AUTH_API_GATEWAY_URL=${gateway_url}
AUTH_API_INTERNAL_URL=$(printf '%s' "$gateway_url" | sed "s#http://localhost:${ministack_port}#http://ministack:4566#")
EOF

info "Auth API will be reached through Ministack API Gateway:"
info "$gateway_url"
